
package com.ruoyi.common.oa;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebService(name = "OA_WorkFlowRequestSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OAWorkFlowRequestSoap {


    /**
     *
     * @param requestid
     * @param clientip
     * @param remark
     * @param forwardoperator
     * @param userId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/forwardWorkflowRequest")
    @WebResult(name = "forwardWorkflowRequestResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "forwardWorkflowRequest", targetNamespace = "http://tempuri.org/", className = "com.chinaztt.mes.common.oa.ForwardWorkflowRequest")
    @ResponseWrapper(localName = "forwardWorkflowRequestResponse", targetNamespace = "http://tempuri.org/", className = "com.chinaztt.mes.common.oa.ForwardWorkflowRequestResponse")
    public String forwardWorkflowRequest(
        @WebParam(name = "requestid", targetNamespace = "http://tempuri.org/")
        int requestid,
        @WebParam(name = "forwardoperator", targetNamespace = "http://tempuri.org/")
        String forwardoperator,
        @WebParam(name = "remark", targetNamespace = "http://tempuri.org/")
        String remark,
        @WebParam(name = "userId", targetNamespace = "http://tempuri.org/")
        int userId,
        @WebParam(name = "clientip", targetNamespace = "http://tempuri.org/")
        String clientip);

    /**
     *
     * @param addWorkflowResult
     * @param errorCode
     * @param appKey
     * @param wri
     * @param errorMsg
     */
    @WebMethod(operationName = "AddWorkflow", action = "http://tempuri.org/AddWorkflow")
    @RequestWrapper(localName = "AddWorkflow", targetNamespace = "http://tempuri.org/", className = "com.chinaztt.mes.common.oa.AddWorkflow")
    @ResponseWrapper(localName = "AddWorkflowResponse", targetNamespace = "http://tempuri.org/", className = "com.chinaztt.mes.common.oa.AddWorkflowResponse")
    public void addWorkflow(
        @WebParam(name = "appKey", targetNamespace = "http://tempuri.org/")
        String appKey,
        @WebParam(name = "wri", targetNamespace = "http://tempuri.org/")
        OAWorkflowRequestInfo wri,
        @WebParam(name = "errorCode", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.INOUT)
        Holder<String> errorCode,
        @WebParam(name = "errorMsg", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.INOUT)
        Holder<String> errorMsg,
        @WebParam(name = "AddWorkflowResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<String> addWorkflowResult);

    /**
     *
     * @param errorCode
     * @param appKey
     * @param updateAndSubmitWorkflowResult
     * @param wri
     * @param errorMsg
     */
    @WebMethod(operationName = "UpdateAndSubmitWorkflow", action = "http://tempuri.org/UpdateAndSubmitWorkflow")
    @RequestWrapper(localName = "UpdateAndSubmitWorkflow", targetNamespace = "http://tempuri.org/", className = "com.chinaztt.mes.common.oa.UpdateAndSubmitWorkflow")
    @ResponseWrapper(localName = "UpdateAndSubmitWorkflowResponse", targetNamespace = "http://tempuri.org/", className = "com.chinaztt.mes.common.oa.UpdateAndSubmitWorkflowResponse")
    public void updateAndSubmitWorkflow(
        @WebParam(name = "appKey", targetNamespace = "http://tempuri.org/")
        String appKey,
        @WebParam(name = "wri", targetNamespace = "http://tempuri.org/")
        OAWorkflowRequestInfo wri,
        @WebParam(name = "errorCode", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.INOUT)
        Holder<String> errorCode,
        @WebParam(name = "errorMsg", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.INOUT)
        Holder<String> errorMsg,
        @WebParam(name = "UpdateAndSubmitWorkflowResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<String> updateAndSubmitWorkflowResult);

}
